[package]
name = "repub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
epub = "2.0.0"
tempfile = "3.7.0"
walkdir = "2.3.2"
zip = "0.6.6"
